/* MegaHub · js/engine/ops.js — rotation validation, delay model, schedule violations + auto-repair, free windows */
function validate(rots,fleet,gates,acId,dst,dep,turn,via,skipIdx){
  const ac=fleet.find(a=>a.id===acId);
  if(!ac)return 'Pick an aircraft';
  if(via){
    if(via===dst)return 'The stop and the destination are the same airport';
    if(via===HUB.c||dst===HUB.c)return 'A rotation cannot stop at its own hub';
  }
  const cand={ac:acId,dst,via:via||null,dep:mod(dep),turn};
  const sh=shape(cand,ac);
  for(const L of sh.legs){
    if(nm(A[L.a],A[L.b])<MIN_STAGE)
      return `${L.a}–${L.b} is ${Math.round(nm(A[L.a],A[L.b]))} nm — nobody flies that, they drive`;
    if(nm(A[L.a],A[L.b])>ac.rng)
      return `${ac.t} can't fly ${L.a}–${L.b} — ${Math.round(nm(A[L.a],A[L.b]))} nm exceeds ${ac.rng} nm range`;
    if((A[L.a].ocean||A[L.b].ocean)&&nm(A[L.a],A[L.b])>OCEAN_LEG&&!ac.etops)
      return `${ac.t} is not certified for extended overwater flight — it cannot fly ${L.a}–${L.b}`;
  }
  const tmin=turnMin(dst,ac);
  if(turn<tmin) return A[dst].intl
    ? `${dst} is a foreign station — ${ac.t} needs ${tmin} min on the ground (customs, security sweep, deep clean)`
    : `${ac.t} needs ${tmin} min on the ground at ${dst}`;
  if(via&&turn<0) return '';
  const mt=minTurnHub(fleet);
  if(sh.dur+mt>DAY)return `Rotation runs ${(sh.dur/60).toFixed(1)}h — no room to turn at the hub`;
  cand.b=sh.legs[0].t; cand.dur=sh.dur; cand.arr=mod(dep+sh.dur);
  const base=rots.filter((_,i)=>i!==skipIdx);
  const all=[...base,cand], rs=acRots(all,acId);
  let total=0;
  for(let i=0;i<rs.length;i++){
    const arr=rs[i].arr,nxt=rs[(i+1)%rs.length].dep;
    const gap=rs.length===1?DAY-rs[i].dur:mod(nxt-arr);
    if(gap<mt)return `${acId} needs ${mt} min on the ground between rotations (has ${Math.round(gap)})`;
    total+=rs[i].dur+gap;
  }
  if(rs.length>1&&Math.abs(total-DAY)>1)return `${acId}'s rotations overlap`;
  // Gate-capacity peak is intentionally NOT blocked here. Mid-build, an aircraft with only
  // its first rotation entered looks like it parks at a gate all day, throwing a false
  // over-capacity error. Real over-capacity is reported at launch (scheduleViolations),
  // which sees the finished day and can auto-repair.
  return null;
}

/* Expected arrival delay, per rotation. Slack absorbs delay; a packed aircraft
   carries the morning's delay all day. Deterministic fixed point, no dice. */
function hubDepPressure(rots){
  /* departures within a +/-15-min window centred on each minute (this airline alone).
     A flight caught in a crowded bank is delayed whether it is early or late in the rush. */
  const dep=new Array(DAY).fill(0);
  rots.forEach(r=>{dep[Math.round(mod(r.dep))%DAY]++;});
  const win=new Array(DAY).fill(0);
  for(let t=0;t<DAY;t++){let c=0; for(let k=-15;k<=15;k++)c+=dep[mod(t+k)]; win[t]=c;}
  return win;
}
/* Expected minutes of delay a leg ADDS. Zero by default: a short flight pushing
   back into an uncrowded bank on an on-time aircraft is on time. Delay appears only
   when a real factor is present — a crowded departure bank, or a long leg's larger
   exposure to weather/ATC beyond a free allowance. */
function legExpDelay(a,b,pressure){
  const d=nm(A[a],A[b]);
  const exposure=DLY_PER_NM*Math.max(0,d-DLY_FREE_NM);          // long legs only
  const congest =DLY_CONGEST*Math.max(0,(pressure||0)-DLY_CONGEST_FREE); // banks over ~2 deps/30min
  return exposure+congest;                                       // can be exactly 0
}
function delayMap(rots,fleet){
  const mt=minTurnHub(fleet), out={}, press=hubDepPressure(rots);
  fleet.forEach(a=>{
    const rs=acRots(rots,a.id); if(!rs.length)return;
    let d=0;
    for(let pass=0;pass<3;pass++){
      for(let i=0;i<rs.length;i++){
        const prev=rs[(i-1+rs.length)%rs.length];
        // inherited delay from the previous rotation, reduced by ground slack before this one
        const gap=rs.length===1?DAY:mod(rs[i].dep-prev.arr);
        if(rs.length>1)d=Math.max(0,d-Math.max(0,gap-mt));  // hub slack absorbs inherited delay
        else d=0;                                            // a lone rotation inherits nothing
        const r=rs[i], p=press[Math.round(mod(r.dep))%DAY];
        // fresh delay generated by THIS departure (congestion + exposure) is not pre-absorbed
        d+=r.via?legExpDelay(HUB.c,r.via,p)+legExpDelay(r.via,r.dst,0)
                :legExpDelay(HUB.c,r.dst,p);
        const outbound=d;                                    // delay as the aircraft sits at the outstation
        d=Math.max(0,d-Math.max(0,r.turn-turnMin(r.dst,a))); // outstation slack absorbs before the return
        d+=r.via?legExpDelay(r.dst,r.via,0)+legExpDelay(r.via,HUB.c,0)
                :legExpDelay(r.dst,HUB.c,0);
        d=Math.min(DELAY_CAP,d);
        // a rotation's delay = the worse of its outbound state and its arrival back at hub,
        // so a congested departure shows even when the long ground turn later recovers it
        out[rots.indexOf(rs[i])]=Math.min(DELAY_CAP,Math.max(outbound,d));
      }
    }
  });
  return out;
}
const otpOf=d=>1/(1+d/90);                     // local passengers dislike a late airline
const pMake=slack=>1/(1+Math.exp(-(slack-8)/6)); // probability a connection actually connects

/* Every rotation must still be legal after the fleet changes.
   Buying a third aircraft type lengthens the hub turn and can strand old rotations. */
function scheduleViolations(rots,fleet,gates){
  const v=[], mt=minTurnHub(fleet);
  fleet.forEach(a=>{
    const rs=acRots(rots,a.id); if(!rs.length)return;
    for(let i=0;i<rs.length;i++){
      const arr=rs[i].arr, nxt=rs[(i+1)%rs.length].dep;
      const gap=rs.length===1?DAY-rs[i].dur:mod(nxt-arr);
      if(gap<mt-0.5) v.push({kind:'turn',ac:a.id,idx:rots.indexOf(rs[(i+1)%rs.length]),
        need:mt,have:Math.round(gap),dst:rs[(i+1)%rs.length].dst});
    }
  });
  const peak=rots.length?Math.max(...gateCurve(rots,fleet)):0;
  if(peak>gates) v.push({kind:'gates',peak,gates});
  return v;
}
/* minimal repair: push the offending departures later, cascading, never reordering */
function repairSchedule(rots,fleet,gates){
  const mt=minTurnHub(fleet);
  const out=rots.map(r=>({...r}));
  for(let pass=0;pass<3;pass++){
    fleet.forEach(a=>{
      const rs=out.filter(r=>r.ac===a.id).sort((x,y)=>x.dep-y.dep);
      if(rs.length<1)return;
      for(let i=0;i<rs.length-1;i++){
        const gap=mod(rs[i+1].dep-rs[i].arr);
        if(gap<mt){const sh=mt-gap; rs[i+1].dep=mod(rs[i+1].dep+sh); rs[i+1].arr=mod(rs[i+1].dep+rs[i+1].dur);}
      }
    });
  }
  const left=scheduleViolations(out,fleet,gates);
  return {ok:left.length===0,rots:out,left};
}
/* when is this aircraft actually free? windows a new rotation could start in */
function freeWindows(rots,fleet,acId){
  const mt=minTurnHub(fleet), rs=acRots(rots,acId);
  if(!rs.length)return [{start:0,len:DAY,full:true}];
  const w=[];
  for(let i=0;i<rs.length;i++){
    const arr=rs[i].arr, nxt=rs[(i+1)%rs.length].dep;
    const gap=rs.length===1?DAY-rs[i].dur:mod(nxt-arr);
    const start=mod(arr+mt), len=gap-2*mt;
    if(len>0)w.push({start,len,after:rs[i].dst});
  }
  return w.sort((a,b)=>b.len-a.len);
}
